---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
ibrary("dplyr")
library("lattice")

if (!file.exists("activity.csv") )
{
  dlurl <- 'https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip'  
  download.file(dlurl,destfile='repdata%2Fdata%2Factivity.zip',mode='wb')  
  unzip('repdata%2Fdata%2Factivity.zip')
}
data <- read.csv("activity.csv")  


## What is mean total number of steps taken per day?
png('steps.png')

mov <- data %>% group_by(date) %>% summarise(steps = sum(steps))
hist(mov$steps, col="light blue",xlab = "Total number of steps by day", main = "Number of steps by day")
mean(mov$steps,na.rm = TRUE)

dev.off()


## What is the average daily activity pattern?
png('interval.png')

median(mov$steps,na.rm = TRUE)
espaço <- data %>% group_by(interval) %>% summarise(steps = mean(steps,na.rm=TRUE))
plot(espaço$interval,espaço$steps,type="l",xlab="5 minutes interval", ylab="Average nº steps",main="Average daily pattern")
espaço$interval[which.max(espaço$steps)]

dev.off()


## Imputing missing values
png('totalpassos.png')
sum(is.na(data$steps))

datatrab <- data
names(espaço)[2] <- "avg_steps"
datamesc <- merge(datatrab,espaço)
datamesc[which(is.na(datamesc$steps)),]$steps <- datamesc[which(is.na(datamesc$steps)),]$avg_steps
datafim <- datamesc[1:3]
mov2 <- datafim %>% group_by(date) %>% summarise(steps = sum(steps))

hist(mov2$steps, col="light blue",xlab = "Number of steps", 
     main = "Total steps per day")

dev.off()

mean(mov2$steps,na.rm = TRUE)
median(mov2$steps,na.rm = TRUE)



## Are there differences in activity patterns between weekdays and weekends?
png('Comparison.png')

datafim <- datafim %>% mutate(day_type = ifelse(grepl("S(at|un)",weekdays(as.Date(datafim$date, 
                                                                                        format = "%Y-%m-%d"))),"weekend","weekday"))
datafim$day_type <- as.factor(datafim$day_type)

espaço2 <- datafim %>% group_by(interval,day_type) %>% summarise(steps = mean(steps,na.rm=TRUE))
xyplot(steps ~ interval | day_type, data = espaço2, type="l",xlab="Interval",ylab="Number of steps",main="Comparison between weekday and weekend activities",
       col.line = "red",
       layout=c(1,2))

dev.off()
